on:
  push:
    paths:
    - "app/**"
jobs:
  coverage-overall:
    name: "Show all coverage files"
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo hello > path/to/artifact/app.txt

    - uses: actions/upload-artifact@v2
      with:
        name: app-artifact
        path: path/to/artifact/app.txt
