on:
  push:
    paths:
    - "framework/**"
jobs:
  coverage-overall:
    name: "Show all coverage files"
    runs-on: "ubuntu-20.04"
    steps:
    - uses: actions/checkout@v2

    - run: mkdir -p path/to/artifact

    - run: echo world > path/to/artifact/framework.txt

    - uses: actions/upload-artifact@v2
      with:
        name: framework-artifact
        path: path/to/artifact/framework.txt
